// import type { Metadata } from "next";
// import React from "react";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/NavBar";
// import Footer from "@/components/Footer";
// import { ThemeProvider } from "next-themes";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       {/* <ThemeProvider enableSystem={true} attribute="class"> */}
//       <Navbar />
//       <body className={inter.className}>{children}</body>
//       <Footer />
//       {/* </ThemeProvider> */}
//     </html>
//   );
// }

"use client";
import "../styles/globals.css";
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { ThemeProvider } from "next-themes";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body className="dark:bg-stone-900 ">
        <ThemeProvider enableSystem={true} attribute="class">
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
